import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Hello from './components/clientComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='w-full h-fit py-[20px]'>
      <body className='flex justify-center items-center w-full h-full'>
        {children}
      </body>
    </html>
  );
}
